### ISSUE TITLE
Bug when adding card

### ISSUE THREAD

**Issue by brittneypostma** [brittneypostma/workflow#18]
When clicking add card, the index's of the Column's change moving them around.
![image](https://user-images.githubusercontent.com/45889730/108100461-f03c1d00-7053-11eb-9f83-4a75ca39cd9e.png)
![image](https://user-images.githubusercontent.com/45889730/108100539-0a75fb00-7054-11eb-847b-35ec30761fcc.png)

**Comment by sz3ry** [comment]
For now there is no card yet, and "add card" button has a reverse function on the store
